spring:
  application:
    name: drugstore
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: <localhost>
    username: <reemplazar con usuario>
    password: <reemplazar con contraseña>
jpa:
  hibernate:
    ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    com.quantify.drugstore: DEBUG

serve.error.include-message: always
